language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t mickey1102/docker-test-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true mickey1102/docker-test-app npm run test

after_success:
  - docker build -t mickey1102/docker-front ./frontend
  - docker build -t mickey1102/docker-back ./backend
  - docker build -t mickey1102/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push mickey1102/docker-front
  - docker push mickey1102/docker-back
  - docker push mickey1102/docker-nginx

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-full"
  env: "Dockerfull-env"
  bucket_name: elasticbeanstalk-ap-northeast-2-380707690899
  bucket_path: "docker-full"
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
